### PR TITLE
add pygsp

### PR DESCRIPTION
**Pull request by mdeff**
I added it below NetworkX as it too visualizes graphs.

### CODE REVIEW

**Comment by jbednar** [comment]
Thanks!

**Comment by jbednar** [comment]
> I added it below NetworkX as it too visualizes graphs.

I moved it to the correct location by download counts (each section is sorted by total downloads (pypi+conda)).  It would be nice to group networkx, pygsp, and graph-tool together, but I think the only way to do that would be to make a new section for "Graph plotting", in which case the descriptive text should mention other tools already listed elsewhere that also do graph plotting (Bokeh, Datashader, HoloViews, Plotly, Matplotlib, etc.).

**Comment by mdeff** [comment]
Ok no prob. Should the ordering be made automatic, or at least documented? I couldn't figure out where I should put it, hence my comment in the PR.

**Comment by mdeff** [comment]
I was too planning to propose the addition of a new section, while adding [igraph](https://igraph.org/python), and maybe [networkit](https://networkit.github.io) and [snap](https://snap.stanford.edu/snappy) (not sure yet about their plotting capabilities). I don't know of generic tools that can plot graphs out-of-the-box. Do you?

**Comment by jbednar** [comment]
Making the ordering automatic is discussed in https://github.com/pyviz/pyviz.org/issues/7#issuecomment-505183974 , and we'd be happy to accept a PR to that effect (or a PR to provide dynamic sorting in JavaScript).

igraph seems fine to add to such a category, but snap seems like it doesn't do much beyond calling gnuplot and graphviz, so it's arguable whether it can be considered a viz tool, and I don't see any plotting in networkit.

**Comment by mdeff** [comment]
[Agreed for snap](https://snap.stanford.edu/snappy/doc/reference/draw.html). Networkit seems to be using [networkx](https://networkit.github.io/dev-docs/python_api/viztasks.html) or [gephi](https://networkit.github.io/dev-docs/python_api/gephi.html). Not really a viz tool either.

**Pull request merged**
