### PR TITLE
Add entry for Great Tables

### PR DESCRIPTION
**Pull request by rich-iannone**
This PR is intended to add [Great Tables](https://github.com/posit-dev/great-tables) as an entry in the `Other InfoVis` category.

### CODE REVIEW

**Comment by rich-iannone** [comment]
Thanks for the quick response! There's actually quite a few that can be considered as table display libraries but still try to include some unexpected visualization/interaction within the table. Here's a short list:

itables: https://github.com/mwouts/itables
buckaroo: https://github.com/paddymul/buckaroo
quak: https://github.com/manzt/quak
reactable: https://github.com/machow/reactable-py

I'm happy to add all of these in a new section if you're up for it :)

**Comment by jbednar** [comment]
Ok, that seems much more compelling than shoehorning great-tables into "other". Thanks! I'd also include [pygwalker](https://github.com/Kanaries/pygwalker). 

I also wonder whether there's a way to include [Tabulator](https://github.com/olifolkerd/tabulator). Tabulator is available as part of [Panel](https://panel.holoviz.org/reference/widgets/Tabulator.html), but listing Panel here would be confusing (since it includes much more than tables), while listing Tabulator is confusing also, since it's JavaScript and needs a wrapper like Panel for people to use it reasonably in Python. The best I can figure is to mention Tabulator in the section's description, with something like:

```
- name: Table display
  intro: Tools for displaying and potentially interacting with data displayed as tables. 
       Data libraries like Pandas and Polars also display tables, as do most dashboarding tools 
       (e.g. Panel includes the Tabulator JS library for interactive tables).
  packages:
    - ...
```

**Comment by rich-iannone** [comment]
pygwalker looks great! Strangely this is the first I’ve heard of it, even though I try to survey what’s around. Definitely will add the two libraries you cited and thanks again!

**Comment by maximlt** [comment]
There's also [perspective](https://github.com/finos/perspective).



> I also wonder whether there's a way to include [Tabulator](https://github.com/olifolkerd/tabulator). Tabulator is available as part of [Panel](https://panel.holoviz.org/reference/widgets/Tabulator.html), but listing Panel here would be confusing (since it includes much more than tables), while listing Tabulator is confusing also, since it's JavaScript and needs a wrapper like Panel for people to use it reasonably in Python. The best I can figure is to mention Tabulator in the section's description, with something like:

App frameworks like Panel usually have their own table components built on top of some JS tabular package. I agree it'd be nice to find a way to list them on this site.

**Comment by jbednar** [comment]
I actually already considered suggesting Perspective, but when I visited their website to get the URL, I saw so few examples involving tables, and so little discussion of tables, that I thought it would be as confusing as including Panel. Plus it's already listed in another section, as Panel is. But if you thought of Perspective immediately too, then I guess yes, add it in this section as well.

**Comment by rich-iannone** [comment]
Just added the table libraries in a new section. Also put in `jupyter-widgets/ipydatagrid`, which is actively maintained and independent of a web/app framework.

**Comment by jbednar** [comment]
Looks great, thanks! Can you fix the indentation? The entries should be lined up under "repo", not under "- repo".

**Comment by rich-iannone** [comment]
Thanks for catching that. All good now!

**Pull request merged**
