### PR TITLE
Add PyData 2021 talks to overviews page

### PR DESCRIPTION
**Pull request by nicolaskruchten**

### CODE REVIEW

**Review by jbednar — APPROVED** [review]
Thanks!

**Comment by nicolaskruchten** [comment]
Uh oh, that didn't do what I thought it would do, sorry!

image

**Comment by nicolaskruchten** [comment]
The italicized link doesn't render as expected... some kind of MD/RST conversion issue?

**Comment by jbednar** [comment]
Yeah, probably why there wasn't a link before. Pure HTML should work...

**Pull request merged**
